project:
  type: website
  output-dir: docs

website:
  title: "filosofia de café"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - I.1.qmd
      - I.2.qmd
      - I.3.qmd
      - I.4.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

