---
title: "I.1"
---

*Brahma é composto por Shiva e Shakti*

**TLDR:** O autor pretende introduzir nos seus comentários as definições de Brahma, Shiva e Shakti. Brahma = oceano; Shiva = oceano calmo; Shakti = força que gera ondas no oceano. Estes três conceitos são desenvolvidos nos próximos sutrams.

Para entender este sutram é preciso ter em conta as seguintes ideias do tantra:

-   os processos que dizemos serem macroscósmicos (não significa externos!) refletem-se de forma microscópica no nosso interior (microcosmos)

-   Em toda a nossa experiência podemos identificar:

    -   a consciência, que é constante no tempo (imutável)

    -   processos dinâmicos, i.e., processos que evoluem no tempo, como são exemplo os nossos pensamentos, emoções e aquilo que observamos pelos sentidos. Estes processos são também designados por objectos da consciência.

-   **Relação:** consciência é necessária aos processos dinâmicos.

-   Esta relação sugere que \[experiênciar um processo dinâmico\] é um novo estado de consciência, para entender o quero dizer por estado usemos a seguinte analogia: cada onda é um novo estado de um oceano originalmente calmo (o estado original = calmo, estado final= ondular). Assim os nossos pensamentos, emoções e o que recolhemos dos sentidos existe dentro de um campo de consciência (=cognição) e são novos estados de consciência.

-   **Brahma** = conjunto das consciências de todos nós (o que inclui - por definição de consciência - todos objectos da consciência)

-   **Shakti** = força que altera o estado calmo do "oceano" de consciência para o estado de "ondas" (objectos da consciência)

-   pensamento e consciência são coisas distintas, um pensamento é um exemplo de um objecto da consciência, uma onda, e que portanto evolui no tempo.

-   **Materialismo** = sistema pensamento (filosófico) que têm como suposição - a matéria é primordial. Tudo o que experênciamos pelos sentidos, a consciência, o pensamento, as emoções etc emergem da matéria. Por exemplo, quando vejo uma rosa, essa experiência emerge do funcionamento do cérebro (matéria). Se o cérebro não existir ou estiver lesionado podemos não ver a cor da rosa ou mesmo a rosa. Donde podemos dizer que o funcionamento do cérebro é necessário à experiência da rosa.

    Mas será o cérebro necessário à consciência ou será a consciência necessária ao cérebro?

    O autor parece sugerir que a última é que está correcta pois a actividade cerebral não passa de algo que observamos e medimos e portanto trata-se de mais um objecto da consciência (processo dinâmico). Conclui-se daqui que a consciência é primordial (segundo o autor)

-   atman (alma) = consciência, "eu sou" puro
