---
title: "I.2"
---

*Esta Shakti é o poder de Shiva.*

**TLDR:** Prakrti é a força que molda o oceano calmo Shiva. Esta força é caracterizada por três gunas, as ondas assim geradas reflectem essas três gunas.

## Comentários + Resumo

-   O oceano de consciência é dotado da capacidade de exercer força sobre si mesmo e de se colocar em movimento e formar ondas (i.e. objectos da consciência)

-   Esta força é designada por Shakti.

-   Não é uma entidade externa a colocar o oceano em movimento, é o próprio oceano que se põem a si em movimento (apenas neste caso poderíamos dizer que o oceano de consciência é tudo o que existe). Shakti não existe independentemente da consciência.

-   Porque é que a palavra "Shiva" surge neste sutram? Pois Shiva é usado \[placeholder\] para oceano de consciência. A razão disto jaz na seguinte imagem:

    Shiva em estado de profunda meditação encontra-se imóvel, mas só até decidir abrir os olhos e começar a fazer cenas. Vemos assim que algo calmo (tal como o oceno de consciência sem objectos da consciência) possui a capacidade de se autocolocar em movimento, é dotado de Shakti.

-   prakrti = Shakti

-   Conceitos Filosóficos úteis:

    Como é que explico um vaso de barro? Como é que respondemos a esta pergunta? A explicação vem em dois tipos:

    -   *O vaso vem da terra, que depois de lhe adicionar água é moldada pela força das mão do oleiro* - Esta é a explicação material (física) é uma sequência de causa efeito. O autor do livro designa isto por Causa Material.

    -   *O vaso existe porque quero plantar flores* - Esta explicação fala do agente, que pensa e deseja. A este explicação é designada por Causa Instrumental.

        Metido nestas dois tipos de explicações de um vaso há um elemento crucial, a força das mãos do oleiro, a esta chamamos de agência conjuntiva. Sinceramente uma designação desnecessariamente complicada, designe-mo-la apenas por força.

-   Com base nestes conceitos filosóficos, podemos dizer que o oceano de consciência é simultaneamente a Causa material e instrumental dos objectos da consciência (ondas), podemos também dizer que prakrti é um agente conjuntivo.

-   Prakrti é um vector de três componentes chamadas de gunas:

    -   Sattvaguna: componente subtil (branco)

    -   Rajoguna: componente mutativa (vermelho)

    -   Tamoguna: componente estática (preto)

    -   (Não entendo esta coloração, mas presumo que a ideia é dizer que as propriedades que as componentes quantificam são análogas a propriedades que tipicamente associamos às cores. Por exemplo o vermelho é a cor que intuitivamente associamos ao perigo, e o perigo diz que se não o respeitarmos as coisas estão prestes a mudar e muito, ora esta propriedade que associamos ao vermelho é análoga à propriedade que a componente rajoguna quantifica)

-   Prakrti origina a experiência de dualidade.

-   **Exemplos de dualidades:** noite-dia, escuro-claro, som-silêncio, mole-duro, ignorância-sabedoria. A nossa experiência do dia a dia exibe não só estes extremos, mas também também os meios termos.

-   Tudo o que experienciamos (macrocósmos) é shakti (prakrti) testemunhado pela consciência (purusa). O autor ao dizer isto está a misturar duas definições de shakti (prakrti) (ver I.3)

-   Processo de criação do Universo (segundo AM):

    A acção de prakrti gera estas "ondas", mas concretamente que ondas são estas? (lista de Kapil)

    1.  Oceano de consciência sem ondas (estado puro), sem atributos, sem qualidades sem limites, livre, sem gunas (ok...onde está shakti...?). I.e. está além da dualidade. Este estado do oceano chamamos de nirguna (sem guna)
    2.  Assim que prakrti actua, o oceano de consciência (purusa/Shiva/brahma) ganha uma onda caracterizada pelas 3 gunas de prakrti. Assim purusa adquire um novo estado a que chamamos de saguna (com guna)
    3.  Inicialmente prakrti gera uma onda que representa o sentido de existência. Se por magia conseguissemos observar esta fase, não teríamos qualquer dificuldade em identificar a consciência universal.
    4.  Prakrti gera ondas que representam a matéria sólida, agora já é mais difícil identificar a consciência universal, esta está a ganhar mais ondas.
    5.  Purusa leva Prakrti a alterar o sentido e a progressivamente acalmar o oceano

-   O autor diz que 1 até 4 temos a fase extrovertida (saincara); a fase 5 é a fase introvertida (pratisaincara). Estas serão revisitadas em mais detalhe nos próximos sutrams.

-   Assim é o casamento de purusa e prakrti.
